Retry for PR with signed commits!
kiwigrid/helm-charts pull request #418
Opened 2021-01-07 22:42 UTC by funkypenguin

#### What this PR does / why we need it:

(this is a retry of https://github.com/kiwigrid/helm-charts/pull/417, since I couldn't get signed commits to work with the a rebase, due to my n00bness)

Adds optional support to the secret-replicator chart for:

1. Passing the `SECRET_NAMESPACE` env var 
2. Setting the pod `securityContext`
3. Setting the container `securityContext`

Why do we need this?

Firstly, in our deployment, we want to isolate secret-replicator from the secrets which it generates.

Secondly, setting `securityContexts` allows "locking-down" the pod in sense of disabling privileged mode, enforcing readOnlyRootFilesystem (only at the container level).

All the changes I've prosposed are opt-in, and I've updated the README accordingly.

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] [DCO](https://developercertificate.org) signed
- [X] Chart Version bumped (if the pr is an update to an existing chart)
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[fluentd-elasticsearch]`)

2021-01-08 16:23 UTC, monotek requested changes

2021-01-08 16:23 UTC, monotek commented on charts/secret-replicator/README.md
> +| `image.tag`                | image tag                                     | `0.1.1`                      |
should be 0.2.0?
also in the values?

2021-01-08 21:23 UTC, funkypenguin commented on charts/secret-replicator/README.md
> +| `image.tag`                | image tag                                     | `0.1.1`                      |
Aah, yes. Sorted :)

2021-01-09 15:52 UTC, monotek approved these changes

2021-01-09 15:52 UTC, merged