Add k8s Service for thanos compactor
kiwigrid/helm-charts pull request #425
Opened 2021-02-05 13:41 UTC by iemre

This also adds an http port mapping for thanos receiver.

Signed-off-by: Emre Kartoglu <iemrek@gmail.com>

Co-authored-by: Tony Di Nucci <tony.dinucci@skyscanner.net>

#### What this PR does / why we need it:

This adds a k8s Service definition for the Thanos Compactor component so we can monitor it using its HTTP `/metrics` endpoint.

This also adds a Service port mapping for the Thanos Receiver component for the same reason i.e. monitoring using the HTTP `/metrics` endpoint.

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://developercertificate.org) signed
- [ ] Chart Version bumped (if the pr is an update to an existing chart)
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[fluentd-elasticsearch]`)

2021-02-05 13:53 UTC, iemre commented on charts/prometheus-thanos/templates/compactor/service.yaml
> +      targetPort: monitoring
corresponds to the port name defined in the StatefulSet definition in `statefulset.yaml`

2021-02-05 17:33 UTC, monotek requested changes

2021-02-05 17:33 UTC, monotek commented on charts/prometheus-thanos/Chart.yaml
> +version: 4.6.1
new feature should raise minor version.

2021-02-05 20:07 UTC, iemre commented
Thanks for the review @monotek. I have just addressed your comment (pushed a new commit).

2021-02-08 08:54 UTC, rpahli approved these changes
LGTM

2021-02-08 08:54 UTC, merged