added imagePullSecrets
kiwigrid/helm-charts pull request #426
Opened 2021-02-11 09:25 UTC by abisare

#### What this PR does / why we need it:

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] [DCO](https://developercertificate.org) signed
- [ ] Chart Version bumped (if the pr is an update to an existing chart)
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[fluentd-elasticsearch]`)

2021-02-11 14:40 UTC, monotek requested changes
please raise minor chart version and sign your commits.

2021-02-11 14:40 UTC, monotek commented on charts/graphite/templates/statefulset.yaml
> +{{- if .Values.pullSecret }}
please add it like:
```
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```

2021-02-11 14:40 UTC, monotek commented on charts/graphite/values.yaml
> +#pullSecret: some-deploy-secret
please add it like:
```
imagePullSecrets: ""
```

2021-02-12 08:35 UTC, rpahli commented
pls also increase the chart version

2021-03-12 13:18 UTC, abisare commented
sorry for late response. fixed

2021-03-12 20:14 UTC, monotek requested changes
New feature should raise minor version

2021-05-25 06:57 UTC, rpahli commented
@abisare can you pls update the minor version and also sing you commits then I can merge the PR.

2021-09-03 02:43 UTC, closed without merging