[prometheus-thanos] Update thanos to 0.20.2
kiwigrid/helm-charts pull request #435
Opened 2021-05-21 12:49 UTC by PaulFarver

#### What this PR does / why we need it:

- Update thanos components to 0.20.2 in order to include all fixes from that version

#### Checklist
- [x] [DCO](https://developercertificate.org) signed
- [x] Chart Version bumped (if the pr is an update to an existing chart)
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[fluentd-elasticsearch]`)

2021-05-21 15:48 UTC, monotek requested changes

2021-05-21 15:48 UTC, monotek commented on charts/prometheus-thanos/Chart.yaml
> +version: 4.8.5
imho this should be a minor update.

2021-05-21 16:35 UTC, PaulFarver commented on charts/prometheus-thanos/Chart.yaml
> +version: 4.8.5
Sounds good. I've updated it

2021-05-25 06:54 UTC, rpahli approved these changes

2021-05-25 06:59 UTC, merged