[graphite] add pod security policy
kiwigrid/helm-charts pull request #450
Opened 2022-05-27 12:14 UTC by davidphay

#### What this PR does / why we need it:
Add pod security policy support

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Special notes for your reviewer:

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://developercertificate.org) signed
- [x] Chart Version bumped (if the pr is an update to an existing chart)
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[fluentd-elasticsearch]`)

2022-06-14 13:02 UTC, davidphay commented
@monotek Hello can you take a look please ?

2022-11-29 16:33 UTC, davidphay commented
@rpahli Hello I rebase the branch it should be good now.

2022-11-29 18:11 UTC, rpahli requested changes

2022-11-29 18:11 UTC, rpahli commented on charts/graphite/templates/_helpers.tpl
> +{{ default "graphite" .Values.serviceAccount.accountName }}
the value `accountName` is not documented. Pls also add this field to the `values.yaml` file and comment it out.

2022-12-02 15:39 UTC, davidphay commented
@rpahli It should be good now

2022-12-02 15:57 UTC, rpahli approved these changes

2022-12-02 15:57 UTC, merged